{{- if .packages.common.darwin.taps }}
# common taps
{{ range .packages.common.darwin.taps -}}
tap "{{ . }}"
{{ end }}
{{- end -}}
{{- if index .packages .profile "darwin" "taps" }}
# {{ .profile }} taps
{{ range index .packages .profile "darwin" "taps" -}}
tap "{{ . }}"
{{ end }}
{{- end -}}
{{- if .packages.common.darwin.formulae }}
# common formulae
{{ range .packages.common.darwin.formulae -}}
brew "{{ . }}"
{{ end }}
{{- end -}}
{{- if index .packages .profile "darwin" "formulae" }}
# {{ .profile }} formulae
{{ range index .packages .profile "darwin" "formulae" -}}
brew "{{ . }}"
{{ end }}
{{- end -}}
{{- if .packages.common.darwin.casks }}
# common casks
{{ range .packages.common.darwin.casks -}}
cask "{{ . }}"
{{ end }}
{{- end -}}
{{- if index .packages .profile "darwin" "casks" }}
# {{ .profile }} casks
{{ range index .packages .profile "darwin" "casks" -}}
cask "{{ . }}"
{{ end }}
{{- end -}}
