#!/usr/bin/env bash

CHEZMOI_SOURCE="$(chezmoi source-path)"
export PATH="${CHEZMOI_SOURCE}/scripts:${PATH}"
source "${CHEZMOI_SOURCE}/scripts/utils.sh"

if ! should_include_secrets; then
  echo_warn "skipping password manager"
  exit 0
fi

if ! command_exists bw; then
  if command_exists brew; then
      install-password-manager
  else
    exit 0
  fi
fi

status="$(bw status)"
status="${status##*\"status\":\"}"
status="${status%%\"*}"

if [[ $status = "unauthenticated" ]]; then
  echo "secret manager is not authenticated, run:"
  echo ""
  echo "  bw login"
  echo ""
  echo "and then to unlock, run:"
  echo ""
  echo "  export BW_SESSION=\$(bw unlock --raw)"
  echo ""
  exit 1
fi

if [[ $status = "locked" ]]; then
  echo "secret manager is locked, run:"
  echo ""
  echo "export BW_SESSION=\$(bw unlock --raw)"
  echo ""
  exit 1
fi

if [[ $status != "unlocked" ]]; then
  echo "secret manager is not unlocked"
  echo ""
  exit 1
fi
