#!/usr/bin/env bash

source "${CHEZMOI_SOURCE_DIR?}/scripts/utils.sh"

if ! command_exists brew; then
    echo_info "installing homebrew"
    local NONINTERACTIVE=1
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if is_arm64; then
    homebrew_bin="/opt/homebrew/bin"
    if ! cat /etc/paths | grep -q "${homebrew_bin}"; then
      echo_info "setting up homebrew binary path"
      echo -e "${homebrew_bin}\n$(cat /etc/paths)" | sudo tee /etc/paths > /dev/null
    fi
fi
